### PR TITLE
Xpmwpf

### PR DESCRIPTION
**Pull request by tofutim**
XPlatformMenus for WPF. It works, depends on a HamburgerMenu git project and still needs icons. Pls review.

### CODE REVIEW

**Comment by benhysell** [comment]
Which HamburgerMenu git project?

**Comment by Cheesebaron** [comment]
Seems like it, yes.

**Comment by tofutim** [comment]
https://github.com/alicanerdogan/HamburgerMenu

need to get some images for the icons

**Comment by tofutim** [comment]
yay for icons, this is ready to pull

wpficons

**Comment by Cheesebaron** [comment]
Just gave it a spin. Looks good. Thanks!

**Pull request merged**
