### PR TITLE
Added UWP implementation with SplitView 

### PR DESCRIPTION
**Pull request by wcoder**
Added UWP implementation with SplitView for #29

Based on https://github.com/wcoder/MvvmCrossStarterKit/tree/feature/uwp-splitview/src/Mobile/Mobile.UWP

### CODE REVIEW

**Comment by martijn00** [comment]
I think we should work together to combine this with #27 

@benhysell How can we get this in line with your PR?

**Comment by benhysell** [comment]
@martijn00 I'm still working through how to remove using ```Messenger``` for changing the presentation.  

I have iOS worked out, although I'm not sure it is the cleanest implementation.  If you could provide some guidance on #27 I can wrap up iOS, start to get Android inline, and then pull in UWP.

**Comment by martijn00** [comment]
@benhysell I am not an expert on that matter, but maybe you could get inspiration from https://github.com/MvvmCross/MvvmCross/pull/1097

Maybe @jamie94bc could share more details with us?

**Comment by benhysell** [comment]
[MvvmCross/MvvmCross#1097](https://github.com/MvvmCross/MvvmCross/pull/1097) is an excellent idea, and that's where I was going to try to go with Android.

For iOS I feel like I have a kludge, the presentation hint is already defined and implemented in the iOS project, in the Mvvmcross iOS support project, and I need to get it down to the PCL project to actually use it.  Right now I'm just passing the hint down to the ```ViewModel``` from the ```View```.  It doesn't feel right.

**Comment by martijn00** [comment]
Thanks!

**Pull request merged**
