### PR TITLE
Remove obsolete AutoView example

### PR DESCRIPTION
**Pull request by Qonstrukt**

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Thanks @Qonstrukt!

**Comment by Qonstrukt** [comment]
It's something

**Comment by Cheesebaron** [comment]
@ghuntley we are slowly luring @Qonstrukt over to the dark side 😄

**Comment by kjeremy** [comment]
HA! I thought I murdered `AutoView` a long time ago.

**Comment by Cheesebaron** [comment]
@kjeremy hehe, it was removed everywhere else except this sample.

**Comment by Qonstrukt** [comment]
@Cheesebaron, nevah!!!
I just ❤️ open source. 😉

**Pull request merged**
