### PR TITLE
Fix #26 XPlatformMenus.Android Match XPlatformMenus.iOS Functionality

### LINKED ISSUE #26: XPlatformMenus.Android Match XPlatformMenus.iOS Functionality
- iOS application has three views off of the hamburger menu, HomeView, HelpView, and SettingsView.  

- HomeView has a button that allows one to navigate to InfoView.  

- InfoView has a button to navigate to ThirdView

- ThirdView has a button to 'save and pop to home view'

Need to create similar functionality for Android

### PR DESCRIPTION
**Pull request by benhysell**
Addresses #26 XPlatformMenus.Android Match XPlatformMenus.iOS Functionality

- Added Messenger plugin and a PopToRootMessage that is listened for in the activity for Android, or custom presenter for iOS to pop the back stack when requested.

- Android - added base.showHamburgerMenu = true; if a fragment should show the hamburger menu

- Android - added ability to save/restore activity's Title when closing an activity.

### CODE REVIEW

**Comment by martijn00** [comment]
There are some cool improvements in here, but i am thinking `MvxMessenger` should not be used for this. Instead a `PresentationHint` should be implemented. Would that be possible?

**Comment by benhysell** [comment]
I went with `MvxMessenger` to allow the other `ViewModels` to listen for the close message and cleanup any resources they had acquired before they are closed.

In my example, ::and maybe these `ViewModel` names should be renamed to be a bit clearer::

- Show `HomeView`, `InfoView`, and `ThirdView`

- Decide to 'save and close' on `ThirdView`, send `PopToRootMessage` from `ThirdViewModel`

- `InfoViewModel` is listening for `PopToRootMessage` and cleans up any resources it had obtained

I had been burned in the past where `InfoViewModel` had subscribed to other messages in the system, I went and popped all the way to root, but did not unsubscribe by hand when the pop happened.  Next time the user navigated down the stack from `HomeView` to `InfoView` I would receive double messages from `MvxMessenger`.  

Thoughts?

**Comment by martijn00** [comment]
This PR might be affected by https://github.com/MvvmCross/MvvmCross-Samples/pull/30

**Comment by benhysell** [comment]
Yes, yes it will...how would you like to proceed?

**Comment by benhysell** [comment]
PresentationHint might work nicely, but I'm not seeing a path to get there.

In the iosSupport I see a new hint, ```MvxPanelPopToRootPresentationHint```, which is exactly what I'd like to use, but I do not have access to it in the ```ThirdViewModel```.  Is the intention that the ```Hint``` to be created in the platform specific project and then resolved somehow in the ```Core``` to be used with ```ChangePresentation```?

**Pull request closed without merging**
