### PR TITLE
Expandable collection sample

### PR DESCRIPTION
**Pull request by tomcurran**

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good!

**Comment by b099l3** [comment]
I couldnt get the [MvxExpandableTableViewSource](https://github.com/MvvmCross/MvvmCross-iOSSupport/blob/master/MvvmCross.iOS.Support/Views/MvxExpandableTableViewSource.cs#L18) to work, see [here](http://stackoverflow.com/a/36852068/1107580). 
Was wondering if I should move this implementation into the iOS support code?

**Comment by b099l3** [comment]
Moved the implementation into the iOS support in this PR #35

**Comment by tomcurran** [comment]
Think you mean https://github.com/MvvmCross/MvvmCross-iOSSupport/pull/35 not #35 on this repo @b099l3

**Comment by b099l3** [comment]
woops! yes.

**Comment by b099l3** [comment]
With MvvmCross/MvvmCross-iOSSupport#35 merged I'll update the sample when the new iOS support package is released.

**Comment by b099l3** [comment]
Thats the sample updated now that Mvx 4.4.0 is out :shipit:

**Pull request merged**
